# Generated by Django 4.2.2 on 2023-07-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=200)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('tel', models.TextField()),
                ('mob', models.TextField()),
                ('mail', models.TextField()),
                ('exhibition', models.TextField(blank=True, null=True)),
                ('contact_person', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('payed', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('employer', models.TextField()),
                ('data', models.TextField(blank=True, null=True)),
                ('logo', models.BinaryField(blank=True, null=True)),
                ('file', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
