# Generated by Django 4.2.2 on 2023-07-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data',
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
