# Generated by Django 4.2.2 on 2023-07-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReg', '0002_remove_user_data_user_date_alter_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employer',
            field=models.TextField(null=True),
        ),
    ]
