# Generated by Django 4.2.2 on 2023-07-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReg', '0004_alter_user_address2_alter_user_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
